// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uudvmlhlgqbloymwkszh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1ZHZtbGhsZ3FibG95bXdrc3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTE0NzUsImV4cCI6MjA3NDk2NzQ3NX0.3qaNFo9hu0hamswBeaWOsu9LBH-bK0QKMM4i2TEHIx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});